### ISSUE TITLE
Crash when moving out of frame

### ISSUE THREAD

**Issue by itsderek23** [luxonis/depthai-python-extras#25]
@Luxonis-Brandon reported that the [reduce_rgb_latency](https://github.com/luxonis/depthai-python-extras/compare/reduce_rgb_latency) branch crashed when he moved out of the frame on the BW1097 when running `python3 test.py`.

Host exception:

```py
Traceback (most recent call last):
  File "test.py", line 120, in <module>
    y1 = int(e[0]['top'] * img_h)
ValueError: cannot convert float NaN to integer
```

My guess is `e[0]['top']` is NaN. This didn't happen every time he left the frame.

**Comment by itsderek23** [comment]
I was not able to replicate this. Idea:

Wrap the coordinate math inside a `try` block and and `continue` on `ValueError` inside an `except` block. Print info on the error inside the `except` block. This will ensure the script doesn't crash if we receive a `NaN` value.

I'm thinking a `try` block versus checking if every number is not `NaN` as most of the time these numbers look fine and doing the check every time adds overhead. Instead, we just handle the few times where things are correct.

/cc @Luxonis-Brandon

**Comment by Luxonis-Brandon** [comment]
Yes, that sounds like an ideal solution to me.  Thanks!

**Comment by itsderek23** [comment]
Closing as it might have ran via old code.
