### ISSUE TITLE
Adjustment of Board Dimensions for Calibration 

### ISSUE THREAD

**Issue by RileyKenyon** [luxonis/depthai-python-extras#49]
The process below describes the steps of modifying `calibration_utils.py` to use a different chessboard size during calibration. Note that width and height are the number of internal corners per a chessboard row and column. A useful link for creating custom chessboards can be found here: https://calib.io/pages/camera-calibration-pattern-generator.

Navigate to the location of the `calibration_utils.py` and make a copy of the original script if interested in comparing
```
cd <INSTALLDIR>/depthai-python-extras/depthai_helpers/
cp calibration_utils.py calibration_utils_py.bak
```
Use the stream editor `sed` to replace the desired values of the script
```
sed -i  '/self.objp\|Chessboard/{
  N
  s/9/<WIDTH>/g
  s/6/<HEIGHT>/g
}' calibration_utils.py
```
Compare the results to confirm the correct lines are replaced
`diff -u calibration_utils.py.bak calibration_utils.py`

The `calibration.py` script should now work for the new board size.  Alternatively, the StereoCalibration class could incorporate the board dimension as an argument.

**Comment by Luxonis-Brandon** [comment]
Hi @RileyKenyon ,

Meant to say earlier thanks a ton for writing this up for us!

Thanks again,
Brandon
