### ISSUE TITLE
Remove default.calib file from version control

### ISSUE THREAD

**Issue by itsderek23** [luxonis/depthai-python-extras#9]
The `resources/default.calib` is currently under version control. I believe this is problematic as it should be overwritten after performing calibration and it's easy to `git push` this board-specific `calib` file on mistake.

Possible alternative:

* Change `default.calib` to `default.calib.example`. Keep this in version control.
* Ignore all files w/the `calib` extension
* When running our example scripts, copy `default.calib.example` => `default.calib` if it doesn't exist.

/cc @Luxonis-Brandon @Luxonis-Brian

**Comment by Luxonis-Brian** [comment]
I agree this is a potential problem. Your plan sounds good, though!

**Comment by itsderek23** [comment]
@Luxonis-Brian implemented an alternative in c66462d40ad64345d4bcf3d7cb56d05e990bc0ed that attempts to load the `depthai.calib` first, then drops down to the default. 

`depthai.calib` is already ignored by version control so I think this solves the root problem.
